// @ts-nocheck
// ==================== KATALOGI SPRZĘTU CCM 2026 + SPORTREBEL ====================
// Dane produktów dla dzieci/młodzik/junior z podziałem na LÓD i ROLKI

// ==================== KATALOG: CCM 2026 - LÓD ====================

export const CCM_LOD_CATALOG = {
  name: "CCM 2026 - Lód (Junior/Youth)",
  supplier: "CCM Hockey / Sport Maska Inc.",
  description: "Oficjalny katalog CCM Hockey 2026 EU - produkty dla dzieci i młodzieży na hokej na lodzie",
};

export const CCM_LOD_PRODUCTS = [
  // ==================== ŁYŻWY YOUTH ====================
  {
    name: "CCM Tacks XR YTH",
    description: "Łyżwy elite z Core Boot Technology. 4 opcje custom color decals do personalizacji butów.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKXR/SKXRY",
    ageGroup: "YT",
    level: "Elite",
    price: 0,
    sizes: ["YT 8", "YT 8.5", "YT 9", "YT 9.5", "YT 10", "YT 11", "YT 11.5", "YT 12", "YT 12.5", "YT 13", "YT 13.5"],
  },
  {
    name: "CCM Tacks XR90 YTH",
    description: "Łyżwy premium Youth. Synthetic composite z custom color decals, pre-sharpened runners.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKXR90",
    ageGroup: "YT",
    level: "Premium",
    price: 0,
    sizes: ["YT 8", "YT 9", "YT 10", "YT 11", "YT 12", "YT 13"],
  },
  {
    name: "CCM Jetspeed FT8 Pro YTH",
    description: "Łyżwy elite Youth. Faux carbon skin, sublimated HD microfiber liner, Step Steel/Blacksteel.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKFT8P",
    ageGroup: "YT",
    level: "Elite",
    price: 0,
    sizes: ["YT 8", "YT 8.5", "YT 9", "YT 9.5", "YT 10", "YT 11", "YT 11.5", "YT 12", "YT 12.5", "YT 13", "YT 13.5"],
  },
  {
    name: "CCM Jetspeed FT890 YTH",
    description: "Łyżwy mid-range Youth. Synthetic composite, pre-sharpened runners, gotowe do jazdy.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SK890",
    ageGroup: "YT",
    level: "Mid",
    price: 0,
    sizes: ["YT 8", "YT 9", "YT 10", "YT 11", "YT 12", "YT 13"],
  },

  // ==================== ŁYŻWY JUNIOR ====================
  {
    name: "CCM Vizion JR",
    description: "Łyżwy elite Junior. Nowa Core Boot Technology, One-Piece Boot, Step Blacksteel runners.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKVZ",
    ageGroup: "JR",
    level: "Elite",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Tacks XR90 JR",
    description: "Łyżwy premium Junior. Core Boot Technology, ADPT Comfort Tongue, XS1 Pro Black runners.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKXR90",
    ageGroup: "JR",
    level: "Premium",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Tacks XR80 JR",
    description: "Łyżwy mid-range Junior. Core Boot Technology, 7mm felt tongue, XS1 Pro Stainless.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKXR80",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Tacks XR70 JR",
    description: "Łyżwy entry Junior. Synthetic comfort, One-Piece Boot, XS1 Stainless Steel runners.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKXR70",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Jetspeed FT8 Pro JR",
    description: "Łyżwy elite Junior. RFM Composite Blend z Super Skin, Step Blacksteel runners.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SKFT8P",
    ageGroup: "JR",
    level: "Elite",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Jetspeed FT890 JR",
    description: "Łyżwy mid-range Junior. RFM Composite Blend, XS1 Pro Stainless runners.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SK890",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Jetspeed FT870 JR",
    description: "Łyżwy entry Junior. Synthetic composite, dodatkowe wsparcie, XS1 Stainless.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SK870",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },
  {
    name: "CCM Jetspeed FT860 JR",
    description: "Łyżwy budget Junior. Synthetic composite, pre-sharpened runners, gotowe do jazdy.",
    brand: "CCM",
    equipmentCategory: "SKATES",
    productCode: "SK860",
    ageGroup: "JR",
    level: "Budget",
    price: 0,
    sizes: ["JR 1", "JR 1.5", "JR 2", "JR 2.5", "JR 3", "JR 3.5"],
  },

  // ==================== KIJE YOUTH ====================
  {
    name: "CCM Jetspeed FT Youth",
    description: "Kij specjalnie dla dzieci. Geometria Youth ułatwia trzymanie kija. Full grip, composite painted blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSJS9Y",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["30 flex 48\" P29", "20 flex 45\" P29", "10 flex 42\" P29"],
  },
  {
    name: "CCM Jetspeed Youth Performance",
    description: "Kij performance Youth. Unikalny profil flex dla dzieci, Sigma STP carbon weave, namebar printer.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSJ10Y3-HSJ40Y3",
    ageGroup: "YT",
    level: "Premium",
    price: 0,
    sizes: ["40 flex 51\" P28/P29", "30 flex 48\" P28/P29", "20 flex 45\" P28/P29", "10 flex 42\" P28"],
  },
  {
    name: "CCM Jetspeed FTW Youth (dziewczęta)",
    description: "Kij Youth zaprojektowany dla dziewcząt. Junior & Youth geometry, full grip.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSFTW26 YTH",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["30 flex 48\" P29"],
  },

  // ==================== KIJE JUNIOR ====================
  {
    name: "CCM Jetspeed FT9 Pro JR",
    description: "Kij elite Junior. Hybrid kickpoint, Neosense Fuze, AlUPli Composite, Evo Blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSFT9P",
    ageGroup: "JR",
    level: "Elite",
    price: 0,
    sizes: ["50 flex 54\" P28/P29/P90TM", "40 flex 51\" P28/P29/P90TM"],
  },
  {
    name: "CCM Jetspeed FT8 JR",
    description: "Kij premium Junior. Hybrid kickpoint, pure carbon technology, JF90 blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSFT8",
    ageGroup: "JR",
    level: "Premium",
    price: 0,
    sizes: ["50 flex 54\" P28/P29/P90TM", "40 flex 51\" P28/P29/P90TM"],
  },
  {
    name: "CCM Jetspeed FT880 JR",
    description: "Kij mid-range Junior. Hybrid kickpoint, Round R geometry, JS4 blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSJ880",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["50 flex 54\" P28/P29", "40 flex 51\" P28/P29"],
  },
  {
    name: "CCM Jetspeed FT860 JR",
    description: "Kij budget Junior. Hybrid kickpoint, Square T geometry, composite stiff blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSJ860",
    ageGroup: "JR",
    level: "Budget",
    price: 0,
    sizes: ["50 flex 54\" P28", "40 flex 51\" P28"],
  },
  {
    name: "CCM Tacks XF JR",
    description: "Kij mid-kick Junior. Modern mid kickpoint, Variable V geometry, Acufeel blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSXF",
    ageGroup: "JR",
    level: "Premium",
    price: 0,
    sizes: ["50 flex 54\" P28¼/P29¼/P90TM", "40 flex 51\" P28¼/P29¼/P90TM"],
  },
  {
    name: "CCM Tacks XF-70 JR",
    description: "Kij mid-kick Junior. Square T geometry, UAF blade with grit finish.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSXF70",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["50 flex 54\" P28/P29", "40 flex 51\" P28/P29"],
  },
  {
    name: "CCM Ribcor Trigger 10 Pro JR/YT",
    description: "Kij elite low-kick. Nanolite Shield, Ergonomic E geometry, Dual-Feel Blade z Helicoid.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSRC10P",
    ageGroup: "JR",
    level: "Elite",
    price: 0,
    sizes: ["50 flex 54\" P28/P29/P90TM", "40 flex 51\" P28/P29/P90TM", "YT 30 flex 48\" P28/P29", "YT 20 flex 45\" P28/P29"],
  },
  {
    name: "CCM Ribcor Trigger 9 JR",
    description: "Kij performance Junior. Pure carbon technology, Ergonomic E geometry, Ascent 3 blade.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSRC9",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["50 flex 54\" P28/P29", "40 flex 51\" P28/P29"],
  },
  {
    name: "CCM Jetspeed FTW Pro JR (dziewczęta)",
    description: "Pierwszy elite kij dla kobiet. Nanolite Shield, X-Soft Blade, zmodyfikowany flex.",
    brand: "CCM",
    equipmentCategory: "STICK",
    productCode: "HSFTWP26",
    ageGroup: "JR",
    level: "Elite",
    price: 0,
    sizes: ["40 flex 51\" P28/P29/P90TM", "YT 30 flex 48\" P28/P29", "YT 20 flex 45\" P28/P29"],
  },

  // ==================== KASKI ====================
  {
    name: "CCM Tacks 310 Junior",
    description: "Kask Junior z R3Flex Protection + Dual Density EVA. Combo z FM580 XS cage. Wiek 7-10 lat.",
    brand: "CCM",
    equipmentCategory: "HELMET",
    productCode: "HT310V26C",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR (49.5-53.5 cm)"],
  },
  {
    name: "CCM Tacks 70 YT",
    description: "Kask Youth z FM70 lightweight cage. Jednorazowy rozmiar dla najmłodszych.",
    brand: "CCM",
    equipmentCategory: "HELMET",
    productCode: "HT70",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["YT (49-53 cm)"],
  },
  {
    name: "CCM Tacks 70 JR",
    description: "Kask Junior z FM70 lightweight cage.",
    brand: "CCM",
    equipmentCategory: "HELMET",
    productCode: "HT70",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR (52.5-57 cm)"],
  },
  {
    name: "CCM Multisport YT",
    description: "Kask multisportowy Youth. Można używać do hokeja na rolkach i innych sportów.",
    brand: "CCM",
    equipmentCategory: "HELMET",
    productCode: "HTMSPRT",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["YT S", "YT M"],
  },

  // ==================== RĘKAWICE ====================
  {
    name: "CCM Next Youth Gloves",
    description: "Rękawice Youth. Pro-level protection z high quality materials.",
    brand: "CCM",
    equipmentCategory: "GLOVES",
    productCode: "NEXT YT",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["8\"", "9\""],
  },
  {
    name: "CCM Next JR Gloves",
    description: "Rękawice Junior. Dobra ochrona i mobilność.",
    brand: "CCM",
    equipmentCategory: "GLOVES",
    productCode: "NEXT JR",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["10\"", "11\"", "12\""],
  },
  {
    name: "CCM Tacks XR80 JR Gloves",
    description: "Rękawice Junior z serii Tacks. Elite Flex Thumb od 11\".",
    brand: "CCM",
    equipmentCategory: "GLOVES",
    productCode: "TACKS XR80",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["10\"", "11\"", "12\""],
  },
  {
    name: "CCM Jetspeed FT8 JR Gloves",
    description: "Rękawice Junior z serii Jetspeed.",
    brand: "CCM",
    equipmentCategory: "GLOVES",
    productCode: "JETSPEED FT8",
    ageGroup: "JR",
    level: "Premium",
    price: 0,
    sizes: ["10\"", "11\"", "12\""],
  },

  // ==================== SPODNIE ====================
  {
    name: "CCM Next Youth Pants",
    description: "Spodnie Youth. Reworked anatomical fit, recreational level.",
    brand: "CCM",
    equipmentCategory: "PANTS",
    productCode: "NEXT YT",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["YT S", "YT M", "YT L"],
  },
  {
    name: "CCM Tacks Pro Youth Pants",
    description: "Spodnie Youth premium. Classic fit z targeted protection dla młodych elite graczy.",
    brand: "CCM",
    equipmentCategory: "PANTS",
    productCode: "TACKS PRO YT",
    ageGroup: "YT",
    level: "Premium",
    price: 0,
    sizes: ["YT S", "YT M", "YT L"],
  },
  {
    name: "CCM Tacks XR JR Pants",
    description: "Spodnie Junior z serii Tacks XR.",
    brand: "CCM",
    equipmentCategory: "PANTS",
    productCode: "TACKS XR JR",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },
  {
    name: "CCM Tacks XR80 JR Pants",
    description: "Spodnie Junior budżetowe z serii Tacks.",
    brand: "CCM",
    equipmentCategory: "PANTS",
    productCode: "TACKS XR80 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },
  {
    name: "CCM Jetspeed FTW JR Pants (dziewczęta)",
    description: "Spodnie Junior damskie z serii FTW.",
    brand: "CCM",
    equipmentCategory: "PANTS",
    productCode: "FTW JR",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },

  // ==================== OCHRANIACZE YOUTH ====================
  {
    name: "CCM Youth Tacks XR Pro Shoulder Pads",
    description: "Naramienniki Youth z serii Tacks XR Pro. Molded PE shoulder caps.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "SPXRPRO YT",
    ageGroup: "YT",
    level: "Premium",
    price: 0,
    sizes: ["YT S", "YT M", "YT L"],
  },
  {
    name: "CCM Youth Elbow Pads",
    description: "Ochraniacze łokci Youth.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "EP YT",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["YT S", "YT M", "YT L"],
  },
  {
    name: "CCM Youth Shin Guards",
    description: "Ochraniacze goleni Youth.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "SG YT",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["YT 8\"", "YT 9\"", "YT 10\""],
  },

  // ==================== OCHRANIACZE JUNIOR ====================
  {
    name: "CCM Tacks XR JR Shoulder Pads",
    description: "Naramienniki Junior z serii Tacks XR.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "SPXR JR",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },
  {
    name: "CCM Tacks XR80 JR Shoulder Pads",
    description: "Naramienniki Junior z serii Tacks XR80.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "SPXR80 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },
  {
    name: "CCM Tacks XR JR Shin Guards",
    description: "Ochraniacze goleni Junior. Injection molded shin cap z D3O.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "SGXR JR",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR 11\"", "JR 12\"", "JR 13\""],
  },
  {
    name: "CCM Tacks XR80 JR Shin Guards",
    description: "Ochraniacze goleni Junior budget.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "SGXR80 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR 11\"", "JR 12\"", "JR 13\""],
  },
  {
    name: "CCM Tacks XR JR Elbow Pads",
    description: "Ochraniacze łokci Junior.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "EPXR JR",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },
  {
    name: "CCM Tacks XR80 JR Elbow Pads",
    description: "Ochraniacze łokci Junior budget.",
    brand: "CCM",
    equipmentCategory: "PADS",
    productCode: "EPXR80 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR S", "JR M", "JR L"],
  },

  // ==================== BRAMKARZ ====================
  {
    name: "CCM Phenom Junior Goalie Set",
    description: "Kompletny zestaw bramkarski Junior. Pads + Blocker + Glove.",
    brand: "CCM",
    equipmentCategory: "GOALIE_GEAR",
    productCode: "PHENOM JR",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["JR S/M", "JR L/XL"],
  },
  {
    name: "CCM Phenom Youth Goalie Set",
    description: "Kompletny zestaw bramkarski Youth dla początkujących bramkarzy.",
    brand: "CCM",
    equipmentCategory: "GOALIE_GEAR",
    productCode: "PHENOM YT",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["YT Regular", "YT Full Right"],
  },

  // ==================== AKCESORIA OBOWIĄZKOWE ====================
  {
    name: "CCM Cut Resistant Neck Guard",
    description: "Ochraniacz szyi ANSI Level 6, certyfikat CE/BNQ/HECC/UKCA. Obowiązkowy w wielu ligach.",
    brand: "CCM",
    equipmentCategory: "NECK_GUARD",
    productCode: "NGCCM26EU",
    ageGroup: "JR",
    level: "Elite",
    price: 0,
    sizes: ["JR S/M"],
  },
  {
    name: "CCM Tether Mouthguard Youth",
    description: "Ochraniacz na zęby z mocowaniem do kasku. Crumple Zone Technology. Idealny do 150cm wzrostu.",
    brand: "CCM",
    equipmentCategory: "MOUTHGUARD",
    productCode: "MG3DGRD Tether",
    ageGroup: "YT",
    level: "Mid",
    price: 0,
    sizes: ["Youth OSFA"],
  },
  {
    name: "CCM Aero Mouthguard",
    description: "Ochraniacz na zęby 50% cieńszy. Można używać z aparatem ortodontycznym.",
    brand: "CCM",
    equipmentCategory: "MOUTHGUARD",
    productCode: "MGAEROGRD",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["S (poniżej 150cm)", "M (150-183cm)", "L (powyżej 183cm)"],
  },
  {
    name: "CCM Deluxe Support with Cup",
    description: "Ochraniacz krocza z suspensorium.",
    brand: "CCM",
    equipmentCategory: "ACCESSORY",
    productCode: "ACJEU",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["YT", "JR", "SR"],
  },

  // ==================== TORBY ====================
  {
    name: "CCM Wheeled Player Bag 32\"",
    description: "Torba hokejowa na kółkach 32\" (115L). Idealna dla juniorów.",
    brand: "CCM",
    equipmentCategory: "BAG",
    productCode: "B520W32",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["32\" (115L)"],
  },
  {
    name: "CCM Carry Player Bag 32\"",
    description: "Torba hokejowa do noszenia 32\" (115L) + mesh bag. Dla juniorów.",
    brand: "CCM",
    equipmentCategory: "BAG",
    productCode: "B51032",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["32\" (115L)"],
  },

  // ==================== SZNURÓWKI ====================
  {
    name: "CCM Waxed Laces",
    description: "Sznurówki woskowane z formowaną końcówką.",
    brand: "CCM",
    equipmentCategory: "ACCESSORY",
    productCode: "LWXLACE",
    ageGroup: "JR",
    level: "Mid",
    price: 0,
    sizes: ["72\" (YT/JR 3)", "84\" (JR 3.5-5.5)"],
  },
];

// ==================== KATALOG: CCM 2026 - ROLKI ====================

export const CCM_ROLKI_CATALOG = {
  name: "CCM 2026 - Rolki (Junior/Youth)",
  supplier: "CCM Hockey / Sport Maska Inc.",
  description: "Oficjalny katalog CCM Hockey 2026 EU - łyżworolki hokejowe i sprzęt do hokeja na rolkach",
};

export const CCM_ROLKI_PRODUCTS = [
  {
    name: "CCM Jetspeed FT890R",
    description: "Łyżworolki elite. RFM Composite Blend z Super Skin, one-piece aluminum chassis, Revision Variant wheels, ABEC 9.",
    brand: "CCM",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "RHFT890",
    ageGroup: "SR/INT",
    level: "Elite",
    price: 0,
    sizes: ["INT 4", "INT 4.5", "INT 5", "INT 5.5", "INT 6", "INT 6.5", "SR 7", "SR 7.5", "SR 8", "SR 8.5", "SR 9", "SR 9.5", "SR 10", "SR 10.5", "SR 11"],
  },
  {
    name: "CCM Jetspeed FT870R",
    description: "Łyżworolki mid. Synthetic composite, Hi-Lo Rizon wheels (outdoor!), ABEC 7.",
    brand: "CCM",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "RHFT870",
    ageGroup: "SR/INT",
    level: "Mid",
    price: 0,
    sizes: ["INT 4", "INT 4.5", "INT 5", "INT 5.5", "INT 6", "INT 6.5", "SR 7", "SR 7.5", "SR 8", "SR 8.5", "SR 9", "SR 9.5", "SR 10", "SR 10.5", "SR 11"],
  },
  {
    name: "CCM Jetspeed FT850R",
    description: "Łyżworolki entry - JEDYNE Z ROZMIAREM JUNIOR! Injected boot, CCM staggered wheels, ABEC 5.",
    brand: "CCM",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "RHFT850",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["JR 1", "JR 2", "JR 3", "INT 4", "INT 5", "INT 6", "SR 7", "SR 8", "SR 9", "SR 10", "SR 11"],
  },
  {
    name: "CCM Street Hockey Goal (duża)",
    description: "Bramka street hockey 72\"x48\"x30\". Spawana stalowa rama, siatka, odporna na warunki atmosferyczne.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "ACGOALCCM",
    ageGroup: "SR",
    level: "Mid",
    price: 0,
    sizes: ["72\" x 48\" x 30\""],
  },
  {
    name: "CCM Street Hockey Goal (mała)",
    description: "Bramka street hockey 54\"x44\"x20\". Idealna dla dzieci.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "ACGOALCCM",
    ageGroup: "JR",
    level: "Entry",
    price: 0,
    sizes: ["54\" x 44\" x 20\""],
  },
  {
    name: "CCM Mini Hockey Set",
    description: "Zestaw mini hokej: 2 mini bramki + 2 kije + 1 piłka. Do rozgrzewki/zabaw.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "ACMINICCM",
    ageGroup: "YT",
    level: "Entry",
    price: 0,
    sizes: ["mini"],
  },
];

// ==================== KATALOG: SPORTREBEL - LÓD ====================

export const SPORTREBEL_LOD_CATALOG = {
  name: "SportRebel - Lód (Junior/Youth)",
  supplier: "SportRebel.com",
  description: "Oferta sklepu SportRebel - sprzęt hokejowy na lód dla dzieci i młodzieży. Ceny detaliczne w EUR.",
};

export const SPORTREBEL_LOD_PRODUCTS = [
  // ==================== ŁYŻWY ====================
  {
    name: "Tempish FS3 Adjustable Hockey Skates",
    description: "Łyżwy regulowane dla dzieci. Rosną z dzieckiem!",
    brand: "Tempish",
    equipmentCategory: "SKATES",
    productCode: "FS3",
    ageGroup: "YT",
    level: "Budget",
    price: 61.14,
    sizes: ["Adjustable"],
  },
  {
    name: "Bauer X-LP Youth Hockey Skates",
    description: "Łyżwy entry level Youth.",
    brand: "Bauer",
    equipmentCategory: "SKATES",
    productCode: "X-LP YT",
    ageGroup: "YT",
    level: "Entry",
    price: 81.59,
    sizes: ["YT sizes"],
  },
  {
    name: "Bauer Lil Rookie Adjustable Youth",
    description: "Łyżwy regulowane Youth Bauer. Rosną z dzieckiem.",
    brand: "Bauer",
    equipmentCategory: "SKATES",
    productCode: "LIL ROOKIE",
    ageGroup: "YT",
    level: "Mid",
    price: 117.95,
    sizes: ["Adjustable"],
  },
  {
    name: "Bauer X-LS Jr Hockey Skates",
    description: "Łyżwy entry level Junior.",
    brand: "Bauer",
    equipmentCategory: "SKATES",
    productCode: "X-LS JR",
    ageGroup: "JR",
    level: "Budget",
    price: 77.05,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer X-LP Jr Hockey Skates",
    description: "Łyżwy entry level Junior.",
    brand: "Bauer",
    equipmentCategory: "SKATES",
    productCode: "X-LP JR",
    ageGroup: "JR",
    level: "Entry",
    price: 106.59,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer X Jr Hockey Skates",
    description: "Łyżwy mid-range Junior.",
    brand: "Bauer",
    equipmentCategory: "SKATES",
    productCode: "X JR",
    ageGroup: "JR",
    level: "Mid",
    price: 167.95,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer VAPOR FLY30 Jr Hockey Skates",
    description: "Łyżwy performance Junior z serii Vapor.",
    brand: "Bauer",
    equipmentCategory: "SKATES",
    productCode: "VAPOR FLY30 JR",
    ageGroup: "JR",
    level: "Premium",
    price: 242.95,
    sizes: ["JR sizes"],
  },

  // ==================== KIJE ====================
  {
    name: "Fischer W150 Kids/Youth/Junior",
    description: "Kij drewniany - najniższy próg wejścia do hokeja!",
    brand: "Fischer",
    equipmentCategory: "STICK",
    productCode: "W150",
    ageGroup: "YT",
    level: "Budget",
    price: 20.23,
    sizes: ["Kids", "Youth", "Junior"],
  },
  {
    name: "Bauer VAPOR Youth '25",
    description: "Kij composite Youth z serii Vapor.",
    brand: "Bauer",
    equipmentCategory: "STICK",
    productCode: "VAPOR YT 25",
    ageGroup: "YT",
    level: "Entry",
    price: 72.50,
    sizes: ["Youth sizes"],
  },
  {
    name: "Bauer X Series '25 JR",
    description: "Kij composite Junior z serii X. GripTac.",
    brand: "Bauer",
    equipmentCategory: "STICK",
    productCode: "X 25 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 72.50,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer NEXUS Performance '24 JR",
    description: "Kij composite Junior z serii Nexus.",
    brand: "Bauer",
    equipmentCategory: "STICK",
    productCode: "NEXUS PERF 24",
    ageGroup: "JR",
    level: "Mid",
    price: 92.95,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer VAPOR FLY40 JR",
    description: "Kij performance Junior z serii Vapor.",
    brand: "Bauer",
    equipmentCategory: "STICK",
    productCode: "VAPOR FLY40 JR",
    ageGroup: "JR",
    level: "Premium",
    price: 122.50,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer VAPOR FLYLITE Jr",
    description: "Kij high-end Junior z serii Vapor.",
    brand: "Bauer",
    equipmentCategory: "STICK",
    productCode: "VAPOR FLYLITE JR",
    ageGroup: "JR",
    level: "Elite",
    price: 192.95,
    sizes: ["JR sizes"],
  },

  // ==================== KASKI ====================
  {
    name: "Bauer Prodigy Yth Helmet",
    description: "Kask Youth. Rozmiary S, M, L.",
    brand: "Bauer",
    equipmentCategory: "HELMET",
    productCode: "PRODIGY",
    ageGroup: "YT",
    level: "Entry",
    price: 61.14,
    sizes: ["S", "M", "L"],
  },
  {
    name: "Bauer RE-AKT 70 Helmet",
    description: "Kask mid-range.",
    brand: "Bauer",
    equipmentCategory: "HELMET",
    productCode: "RE-AKT 70",
    ageGroup: "JR",
    level: "Mid",
    price: 102.05,
    sizes: ["M", "L"],
  },
  {
    name: "Bauer RE-AKT 90 Helmet",
    description: "Kask premium.",
    brand: "Bauer",
    equipmentCategory: "HELMET",
    productCode: "RE-AKT 90",
    ageGroup: "JR",
    level: "Premium",
    price: 152.05,
    sizes: ["M", "L"],
  },

  // ==================== RĘKAWICE ====================
  {
    name: "Bauer Supreme X '24 Youth Gloves",
    description: "Rękawice Youth entry level.",
    brand: "Bauer",
    equipmentCategory: "GLOVES",
    productCode: "SUPREME X 24 YT",
    ageGroup: "YT",
    level: "Entry",
    price: 61.14,
    sizes: ["8\"", "9\""],
  },
  {
    name: "Bauer Supreme X '24 Jr Gloves",
    description: "Rękawice Junior entry level.",
    brand: "Bauer",
    equipmentCategory: "GLOVES",
    productCode: "SUPREME X 24 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 65.68,
    sizes: ["10\"", "11\"", "12\"", "13\""],
  },
  {
    name: "Bauer VAPOR FLY40 Jr Gloves",
    description: "Rękawice Junior mid-range z serii Vapor.",
    brand: "Bauer",
    equipmentCategory: "GLOVES",
    productCode: "VAPOR FLY40 JR",
    ageGroup: "JR",
    level: "Mid",
    price: 102.05,
    sizes: ["10\"", "11\"", "12\"", "13\""],
  },

  // ==================== SPODNIE ====================
  {
    name: "Bauer X '24 Youth Pants",
    description: "Spodnie Youth entry level.",
    brand: "Bauer",
    equipmentCategory: "PANTS",
    productCode: "X 24 YT",
    ageGroup: "YT",
    level: "Entry",
    price: 52.05,
    sizes: ["S", "M", "L"],
  },
  {
    name: "Bauer X '24 Jr Pants",
    description: "Spodnie Junior entry level.",
    brand: "Bauer",
    equipmentCategory: "PANTS",
    productCode: "X 24 JR",
    ageGroup: "JR",
    level: "Entry",
    price: 61.14,
    sizes: ["M", "L"],
  },
  {
    name: "Bauer Supreme Mach Youth Pants",
    description: "Spodnie Youth premium.",
    brand: "Bauer",
    equipmentCategory: "PANTS",
    productCode: "SUPREME MACH YT",
    ageGroup: "YT",
    level: "Premium",
    price: 72.50,
    sizes: ["S", "M", "L"],
  },

  // ==================== OCHRANIACZE ====================
  {
    name: "Bauer X '24 Youth Shoulder Pads",
    description: "Naramienniki Youth.",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X 24 SP YT",
    ageGroup: "YT",
    level: "Entry",
    price: 52.05,
    sizes: ["S", "M"],
  },
  {
    name: "Bauer X '24 Jr Shoulder Pads",
    description: "Naramienniki Junior.",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X 24 SP JR",
    ageGroup: "JR",
    level: "Entry",
    price: 56.59,
    sizes: ["M", "L"],
  },
  {
    name: "Bauer X Youth Shin Guards",
    description: "Ochraniacze goleni Youth.",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X SG YT",
    ageGroup: "YT",
    level: "Entry",
    price: 45.23,
    sizes: ["Youth sizes"],
  },
  {
    name: "Bauer X '24 Jr Shin Guards",
    description: "Ochraniacze goleni Junior.",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X 24 SG JR",
    ageGroup: "JR",
    level: "Entry",
    price: 56.59,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer X Youth Elbow Pads",
    description: "Ochraniacze łokci Youth.",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X EP YT",
    ageGroup: "YT",
    level: "Entry",
    price: 27.05,
    sizes: ["Youth sizes"],
  },
  {
    name: "Bauer X '24 Jr Elbow Pads",
    description: "Ochraniacze łokci Junior.",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X 24 EP JR",
    ageGroup: "JR",
    level: "Entry",
    price: 38.41,
    sizes: ["JR sizes"],
  },

  // ==================== OCHRANIACZE SZYI ====================
  {
    name: "Bauer NLP21 Children's Neck Guard",
    description: "Ochraniacz szyi dla dzieci.",
    brand: "Bauer",
    equipmentCategory: "NECK_GUARD",
    productCode: "NLP21",
    ageGroup: "YT",
    level: "Entry",
    price: 27.05,
    sizes: ["XS", "S/M", "L/XL"],
  },
  {
    name: "Bauer NLP7 Youth Core Neck Guard",
    description: "Ochraniacz szyi Youth budget.",
    brand: "Bauer",
    equipmentCategory: "NECK_GUARD",
    productCode: "NLP7",
    ageGroup: "YT",
    level: "Budget",
    price: 17.95,
    sizes: ["S/M", "L/XL"],
  },

  // ==================== ZESTAWY STARTOWE ====================
  {
    name: "Fischer Starter Kit Jr",
    description: "Kompletny zestaw ochronny Junior - naramienniki, łokcie, golenie w jednym zakupie!",
    brand: "Fischer",
    equipmentCategory: "PADS",
    productCode: "STARTER KIT JR",
    ageGroup: "JR",
    level: "Entry",
    price: 172.50,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer Vapor X-Tend Full Protection Kit",
    description: "Pełny zestaw ochronny dla dzieci - wszystko czego potrzebujesz w jednym pudełku!",
    brand: "Bauer",
    equipmentCategory: "PADS",
    productCode: "X-TEND KIT",
    ageGroup: "YT",
    level: "Entry",
    price: 202.05,
    sizes: ["Kids sizes"],
  },
];

// ==================== KATALOG: SPORTREBEL - ROLKI ====================

export const SPORTREBEL_ROLKI_CATALOG = {
  name: "SportRebel - Rolki (Junior/Youth)",
  supplier: "SportRebel.com",
  description: "Oferta sklepu SportRebel - łyżworolki hokejowe i rekreacyjne dla dzieci i młodzieży",
};

export const SPORTREBEL_ROLKI_PRODUCTS = [
  {
    name: "Mission Inhaler NLS:06 Youth",
    description: "Łyżworolki hokejowe Youth - entry level.",
    brand: "Mission",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "NLS:06 YT",
    ageGroup: "YT",
    level: "Entry",
    price: 119.32,
    sizes: ["Youth sizes"],
  },
  {
    name: "Bauer RH X-LP Jr (Adjustable)",
    description: "Łyżworolki hokejowe Junior regulowane. Rosną z dzieckiem!",
    brand: "Bauer",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "RH X-LP JR",
    ageGroup: "JR",
    level: "Entry",
    price: 138.41,
    sizes: ["Adjustable JR"],
  },
  {
    name: "Bauer RH RSX Jr",
    description: "Łyżworolki hokejowe Junior mid-range.",
    brand: "Bauer",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "RH RSX JR",
    ageGroup: "JR",
    level: "Mid",
    price: 167.95,
    sizes: ["JR sizes"],
  },
  {
    name: "Bauer Vapor X3.5 Jr Roller Skates",
    description: "Łyżworolki hokejowe Junior performance.",
    brand: "Bauer",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "VAPOR X3.5 JR",
    ageGroup: "JR",
    level: "Premium",
    price: 192.95,
    sizes: ["JR sizes"],
  },
  {
    name: "FunActiv Twixer Adjustable Kids",
    description: "Łyżworolki rekreacyjne regulowane dla dzieci. Budżetowa opcja na start.",
    brand: "FunActiv",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "TWIXER",
    ageGroup: "YT",
    level: "Budget",
    price: 61.14,
    sizes: ["Adjustable"],
  },
  {
    name: "Tempish Sunny Leopard Kids",
    description: "Łyżworolki rekreacyjne dla dzieci.",
    brand: "Tempish",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "SUNNY LEOPARD",
    ageGroup: "YT",
    level: "Budget",
    price: 77.05,
    sizes: ["Kids sizes"],
  },
  {
    name: "Tempish Verso Triple II",
    description: "Łyżworolki rekreacyjne 3w1 (inline/quad/ice).",
    brand: "Tempish",
    equipmentCategory: "ROLLER_SKATES",
    productCode: "VERSO TRIPLE II",
    ageGroup: "YT",
    level: "Entry",
    price: 90.68,
    sizes: ["Kids sizes"],
  },
];

// ==================== KATALOG: POMOCE TRENINGOWE ====================

export const TRAINING_AIDS_CATALOG = {
  name: "Pomoce treningowe - SWH (CCM + SportRebel)",
  supplier: "CCM / SportRebel / Różni producenci",
  description: "Pomoce treningowe dla trenerów SWH - sprzęt do treningu na lodzie, sucho i na rolkach",
};

export const TRAINING_AIDS_PRODUCTS = [
  // ==================== CCM ====================
  {
    name: "CCM Coaching Board",
    description: "Tablica trenerska 350x250mm. Pełne lodowisko z jednej strony, połówka z drugiej. Metalowy klips z długopisem.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "ACBOARD",
    ageGroup: null,
    level: "Mid",
    price: 0,
    sizes: ["350mm x 250mm"],
  },
  {
    name: "CCM Ice Shooter Tutor",
    description: "Cel na bramkę 72\"x48\" z 5 otworami i 4 kieszeniami siatkowymi. Mocowanie bungee.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "ACTUTOICE",
    ageGroup: null,
    level: "Mid",
    price: 0,
    sizes: ["72\" x 48\""],
  },
  {
    name: "CCM Deluxe Puck Bag",
    description: "Torba na ~60 krążków. Foam-insulated, 1680D polyester.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "BPUCKD",
    ageGroup: null,
    level: "Mid",
    price: 0,
    sizes: ["11\" x 13\" x 9\""],
  },
  {
    name: "CCM Team Wheeled Stick Bag",
    description: "Torba drużynowa na 70+ kijów. Na kółkach, tarpaulin.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "BTMSTW",
    ageGroup: null,
    level: "Mid",
    price: 0,
    sizes: ["77\" x 10\" x 15\""],
  },
  {
    name: "CCM Water Bottle 1000ml",
    description: "Bidon 1000ml, BPA free, silikonowa słomka.",
    brand: "CCM",
    equipmentCategory: "ACCESSORY",
    productCode: "ACBOTTLE26",
    ageGroup: null,
    level: "Entry",
    price: 0,
    sizes: ["1000ml"],
  },
  {
    name: "CCM Skate Oven",
    description: "Piec do termicznego formowania łyżew.",
    brand: "CCM",
    equipmentCategory: "TRAINING_AID",
    productCode: "ACUPLU",
    ageGroup: null,
    level: "Elite",
    price: 0,
    sizes: ["OSFA"],
  },

  // ==================== SPORTREBEL ====================
  {
    name: "BlueSports Target Tethers 4-pack",
    description: "Zestaw 4 celów do montażu na bramce. Do ćwiczeń celności strzału.",
    brand: "BlueSports",
    equipmentCategory: "TRAINING_AID",
    productCode: "TARGET TETHERS",
    ageGroup: null,
    level: "Entry",
    price: 13.41,
    sizes: ["4-pack"],
  },
  {
    name: "BlueSports Magnetic Target Set for Goal",
    description: "Magnetyczne cele na bramkę. Łatwy montaż i demontaż.",
    brand: "BlueSports",
    equipmentCategory: "TRAINING_AID",
    productCode: "MAG TARGET",
    ageGroup: null,
    level: "Mid",
    price: 97.50,
    sizes: ["Goal size"],
  },
  {
    name: "BlueSports Attack Triangle 3D Obstacle",
    description: "Trójkąt atakujący 3D - przeszkoda treningowa do ćwiczeń stickhandlingu.",
    brand: "BlueSports",
    equipmentCategory: "TRAINING_AID",
    productCode: "ATTACK TRIANGLE",
    ageGroup: null,
    level: "Mid",
    price: 102.05,
    sizes: ["OSFA"],
  },
  {
    name: "Bauer Reactor Stickhandling Trainer",
    description: "Trener stickhandlingu. Rozwijanie umiejętności prowadzenia krążka.",
    brand: "Bauer",
    equipmentCategory: "TRAINING_AID",
    productCode: "REACTOR SH",
    ageGroup: null,
    level: "Mid",
    price: 81.59,
    sizes: ["OSFA"],
  },
  {
    name: "Bauer Reactor Stickhandling Extendible 3",
    description: "Rozszerzalny trener stickhandlingu - 3 sekcje.",
    brand: "Bauer",
    equipmentCategory: "TRAINING_AID",
    productCode: "REACTOR SH EXT",
    ageGroup: null,
    level: "Premium",
    price: 165.68,
    sizes: ["OSFA"],
  },
  {
    name: "Bauer Digital Reactor Stickhandling",
    description: "Cyfrowy trener stickhandlingu z podświetleniem LED.",
    brand: "Bauer",
    equipmentCategory: "TRAINING_AID",
    productCode: "DIGITAL REACTOR",
    ageGroup: null,
    level: "Elite",
    price: 220.23,
    sizes: ["OSFA"],
  },
  {
    name: "Hockey Revolution My Hockey Enemy System",
    description: "System treningowy - atrapa zawodnika do ćwiczeń omijania i strzałów.",
    brand: "Hockey Revolution",
    equipmentCategory: "TRAINING_AID",
    productCode: "ENEMY SYSTEM",
    ageGroup: null,
    level: "Mid",
    price: 61.14,
    sizes: ["OSFA"],
  },
  {
    name: "Hockey Revolution Drill Sticks",
    description: "Kije treningowe do ćwiczeń slalomowych i stickhandlingu.",
    brand: "Hockey Revolution",
    equipmentCategory: "TRAINING_AID",
    productCode: "DRILL STICKS",
    ageGroup: null,
    level: "Mid",
    price: 81.59,
    sizes: ["OSFA"],
  },
  {
    name: "Hockey Revolution My Hockey Training Surface",
    description: "Powierzchnia treningowa do ćwiczeń stickhandlingu i strzałów w domu.",
    brand: "Hockey Revolution",
    equipmentCategory: "TRAINING_AID",
    productCode: "TRAINING SURFACE",
    ageGroup: null,
    level: "Mid",
    price: 102.05,
    sizes: ["OSFA"],
  },
  {
    name: "Hockey Revolution Slideboard Lit",
    description: "Slideboard do ćwiczeń poślizgu i balansu.",
    brand: "Hockey Revolution",
    equipmentCategory: "TRAINING_AID",
    productCode: "SLIDEBOARD",
    ageGroup: null,
    level: "Premium",
    price: 174.77,
    sizes: ["OSFA"],
  },
  {
    name: "Bauer Dryland Training Tiles",
    description: "Płytki do treningu na sucho - syntetyczny lód.",
    brand: "Bauer",
    equipmentCategory: "TRAINING_AID",
    productCode: "DRYLAND TILES",
    ageGroup: null,
    level: "Premium",
    price: 158.86,
    sizes: ["Pack"],
  },
  {
    name: "Bauer Shooting Pad Reactor",
    description: "Mata do ćwiczeń strzałów - symulacja lodu.",
    brand: "Bauer",
    equipmentCategory: "TRAINING_AID",
    productCode: "SHOOTING PAD",
    ageGroup: null,
    level: "Premium",
    price: 206.59,
    sizes: ["OSFA"],
  },
  {
    name: "Bauer Passer Reactor Slingshot 48",
    description: "Passer/rebounder do ćwiczeń podań i przyjęć. 48\".",
    brand: "Bauer",
    equipmentCategory: "TRAINING_AID",
    productCode: "SLINGSHOT 48",
    ageGroup: null,
    level: "Elite",
    price: 292.95,
    sizes: ["48\""],
  },
  {
    name: "Digital Response Pods",
    description: "Cyfrowe pody reakcyjne do ćwiczeń szybkości reakcji.",
    brand: "Generic",
    equipmentCategory: "TRAINING_AID",
    productCode: "RESPONSE PODS",
    ageGroup: null,
    level: "Elite",
    price: 233.86,
    sizes: ["Set"],
  },
  {
    name: "Radar Gun (pomiar prędkości)",
    description: "Radar do pomiaru prędkości strzału.",
    brand: "Generic",
    equipmentCategory: "TRAINING_AID",
    productCode: "RADAR GUN",
    ageGroup: null,
    level: "Premium",
    price: 131.59,
    sizes: ["OSFA"],
  },
  {
    name: "Tempish Training Jersey Basic",
    description: "Koszulka treningowa. Różne kolory do podziału na drużyny.",
    brand: "Tempish",
    equipmentCategory: "TRAINING_AID",
    productCode: "JERSEY BASIC",
    ageGroup: null,
    level: "Budget",
    price: 8.86,
    sizes: ["OSFA"],
  },
  {
    name: "Sidelines Field Markers",
    description: "Markery na lodowisko/boisko do oznaczania stref i ćwiczeń.",
    brand: "Sidelines",
    equipmentCategory: "TRAINING_AID",
    productCode: "FIELD MARKERS",
    ageGroup: null,
    level: "Budget",
    price: 2.05,
    sizes: ["OSFA"],
  },
  {
    name: "Sidelines Stopwatch Chronos",
    description: "Stoper treningowy.",
    brand: "Sidelines",
    equipmentCategory: "TRAINING_AID",
    productCode: "CHRONOS",
    ageGroup: null,
    level: "Budget",
    price: 11.14,
    sizes: ["OSFA"],
  },
  {
    name: "Tempish Skate Helper (Rental)",
    description: "Pomocnik do nauki jazdy na łyżwach - do wypożyczalni.",
    brand: "Tempish",
    equipmentCategory: "TRAINING_AID",
    productCode: "SKATE HELPER",
    ageGroup: "YT",
    level: "Entry",
    price: 67.95,
    sizes: ["OSFA"],
  },
  {
    name: "BlueSports Training System (synthetic ice)",
    description: "System treningowy z syntetycznym lodem.",
    brand: "BlueSports",
    equipmentCategory: "TRAINING_AID",
    productCode: "SYNTHETIC ICE",
    ageGroup: null,
    level: "Mid",
    price: 33.86,
    sizes: ["Pack"],
  },
];
